#!/bin/sh

bindir=$(dirname "$(readlink -nf $0)")

libdir=$(cd "${bindir}/../lib" ; pwd)

LD_LIBRARY_PATH="/opt/qt-beta1/lib:${libdir}/qtcreator:${LD_LIBRARY_PATH}" exec "${bindir}/qtcreator.bin" ${1+"$@"}
